import { Lead, SurveyResponse, DashboardMetrics } from '@/types';

export const MOCK_LEADS: Lead[] = [
  {
    id: 'L-101',
    customerName: 'Aditya Sharma',
    phone: '+91 98765 43210',
    email: 'aditya.sharma@gmail.com',
    address: 'Flat 402, Sunshine Heights, Sector 15, Dwarka, New Delhi',
    monthlyBill: 4500,
    avgUsageKwh: 450,
    roofAreaSqFt: 600,
    roofType: 'concrete',
    status: 'new',
    assignedExecutive: 'Manish Bharodiya',
    createdAt: '2026-06-15T10:30:00Z',
  },
  {
    id: 'L-102',
    customerName: 'Meera Deshmukh',
    phone: '+91 87654 32109',
    email: 'meera.d@yahoo.com',
    address: 'Row House 12, Green Meadows, Baner, Pune',
    monthlyBill: 8200,
    avgUsageKwh: 800,
    roofAreaSqFt: 1200,
    roofType: 'tiles',
    status: 'survey-scheduled',
    assignedExecutive: 'Manish Bharodiya',
    createdAt: '2026-06-14T09:15:00Z',
  },
  {
    id: 'L-103',
    customerName: 'Karthik Raja',
    phone: '+91 76543 21098',
    email: 'karthik.raja@outlook.com',
    address: 'No 45, 3rd Cross, Indiranagar, Bengaluru',
    monthlyBill: 6100,
    avgUsageKwh: 580,
    roofAreaSqFt: 850,
    roofType: 'concrete',
    status: 'survey-completed',
    assignedExecutive: 'Priya Nair',
    createdAt: '2026-06-12T14:45:00Z',
  },
  {
    id: 'L-104',
    customerName: 'Sunita Gupta',
    phone: '+91 95432 10987',
    email: 'sunita.gupta@rediffmail.com',
    address: 'B-124, Shanti Kunj, Salt Lake, Kolkata',
    monthlyBill: 12500,
    avgUsageKwh: 1150,
    roofAreaSqFt: 2200,
    roofType: 'concrete',
    status: 'converted',
    assignedExecutive: 'Priya Nair',
    createdAt: '2026-06-10T11:00:00Z',
  },
  {
    id: 'L-105',
    customerName: 'Vikram Singh',
    phone: '+91 91234 56789',
    email: 'vikram.singh@gmail.com',
    address: 'Farmhouse 4, DLF Chattarpur, New Delhi',
    monthlyBill: 24000,
    avgUsageKwh: 2200,
    roofAreaSqFt: 3500,
    roofType: 'tin-shed',
    status: 'contacted',
    assignedExecutive: 'Manish Bharodiya',
    createdAt: '2026-06-14T16:20:00Z',
  },
  {
    id: 'L-106',
    customerName: 'Anil Mehta',
    phone: '+91 88990 11223',
    email: 'mehta.anil@gmail.com',
    address: 'Plot 78, Sector 4, Vashi, Navi Mumbai',
    monthlyBill: 9800,
    avgUsageKwh: 920,
    roofAreaSqFt: 1000,
    roofType: 'concrete',
    status: 'lost',
    assignedExecutive: 'Priya Nair',
    createdAt: '2026-06-08T10:00:00Z',
  }
];

export const MOCK_SURVEYS: SurveyResponse[] = [
  {
    id: 'S-201',
    leadId: 'L-103',
    hasShading: false,
    connectionType: 'three-phase',
    sanctionedLoadKw: 8,
    structuralStability: 'excellent',
    remarks: 'Clear roof area with no obstacles. Recommended 6 kW solar system installation.',
    coordinates: {
      latitude: 12.9716,
      longitude: 77.5946,
    },
    surveyorName: 'Priya Nair',
    surveyDate: '2026-06-13T11:30:00Z',
  },
  {
    id: 'S-202',
    leadId: 'L-104',
    hasShading: true,
    connectionType: 'three-phase',
    sanctionedLoadKw: 15,
    structuralStability: 'good',
    remarks: 'Water tank casting shade on west side. Placed array structure on east facing corner. Approved for 12 kW solar system.',
    coordinates: {
      latitude: 22.5726,
      longitude: 88.3639,
    },
    surveyorName: 'Priya Nair',
    surveyDate: '2026-06-11T15:00:00Z',
  }
];

export const MOCK_METRICS: DashboardMetrics = {
  totalLeads: 248,
  newLeads: 42,
  surveysCompleted: 156,
  conversionRate: 24.5,
  targetLeadsThisMonth: 100,
  leadsAchievedThisMonth: 68
};
